version: '3.0'
services:
  database: 
    image: postgres:latest
    volumes:
      - ./datasource:/home/datasource
      - ./scripts:/home/scripts
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:rx
    ports:
      - 5432:5432
    env_file:
      - ./.env
    networks:
      - default
  pgadmin: 
    image: dpage/pgadmin4
    ports:
      - 80:80
    networks:
      - default
    depends_on:
      - database
    env_file:
      - ./.env
networks:
  default:
      name: db-connection 
      driver: bridge
